language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '5'
  - '4'
script:
  - npm run test
branches:
  only:
    - master
