branches:
  only:
  - master

environment:
  nodejs_version: '7'

install:
  - choco install googlechrome
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off
version: '{build}'
shallow_clone: true
clone_depth: 1

test_script:
  - node --version
  - npm --version
  - npm test

artifacts:
  - path: reports
    name: Reports
